const STORAGE_KEY='mindcare_v3';
const therapists=[
 {id:'dr-sara',name:'د. سارة أحمد',role:'أخصائية نفسية',bio:'جلسات فردية ودعم نفسي للبالغين',initials:'س'},
 {id:'dr-omar',name:'د. عمر خالد',role:'معالج نفسي',bio:'العلاج المعرفي السلوكي وإدارة الضغوط',initials:'ع'},
 {id:'dr-mona',name:'د. منى علي',role:'أخصائية نفسية',bio:'الدعم النفسي والعلاقات والمهارات الحياتية',initials:'م'}
];
const services=[
 {id:'consult',name:'استشارة نفسية',description:'جلسة مهنية لفهم الاحتياج ووضع الخطوات المناسبة.'},
 {id:'followup',name:'جلسة متابعة',description:'متابعة التقدم ومراجعة الخطة والمهارات.'}
];
const defaultData={settings:{currency:'EGP',prices:{30:500,60:900}},availability:{'dr-sara':{'2026-09-09':['09:00','09:30','10:00','10:30','11:00','17:00','17:30','18:00']},'dr-omar':{'2026-09-09':['10:00','10:30','11:00','17:00','17:30'],'2026-09-10':['10:00','10:30','11:00','17:00','18:00']},'dr-mona':{'2026-09-10':['09:00','09:30','10:00','10:30','11:00','16:00','16:30'] }},bookings:[]};
let db=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')||structuredClone(defaultData);
if(!db.availability||Array.isArray(db.availability)){const old=Array.isArray(db.availability)?db.availability:[];db.availability={'dr-sara':{}};old.forEach(x=>db.availability['dr-sara'][x.date]=x.slots);save()}
let booking={serviceId:null,therapistId:null,duration:null,date:null,time:null};
const app=document.getElementById('app');
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(db))}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function render(content){app.innerHTML=`<div class="container">${content}<div class="footer">MindCare PWA — النسخة التجريبية v0.3</div></div>`}
function go(page){location.hash=page}
function home(){render(`<section class="hero"><span class="badge">MindCare</span><h1>رعايتك النفسية تبدأ بخطوة</h1><p>اختر الخدمة والأخصائي والموعد المناسب لك بسهولة.</p><button class="btn" onclick="go('book')">احجز جلسة جديدة</button></section><section class="section"><h2>خدماتنا</h2><div class="grid">${services.map(s=>`<div class="card"><h3>${s.name}</h3><p>${s.description}</p></div>`).join('')}</div></section>`)}
function steps(active){return `<div class="step">${['الخدمة','الأخصائي','المدة','التاريخ','الوقت','البيانات'].map((x,i)=>`<span class="${i===active?'active':''}">${i+1}. ${x}</span>`).join('')}</div>`}
function book(){render(`${steps(0)}<h2>اختر نوع الخدمة</h2><div class="grid">${services.map(s=>`<div class="card"><h3>${s.name}</h3><p>${s.description}</p><button class="btn" onclick="selectService('${s.id}')">اختيار</button></div>`).join('')}</div><button class="btn secondary" onclick="go('home')">رجوع</button>`)}
function selectService(id){booking={serviceId:id,therapistId:null,duration:null,date:null,time:null};chooseTherapist()}
function chooseTherapist(){render(`${steps(1)}<h2>اختر الأخصائي</h2><div class="grid">${therapists.map(t=>`<div class="card"><div class="doctor"><div class="avatar">${t.initials}</div><div><h3>${t.name}</h3><div>${t.role}</div></div></div><p>${t.bio}</p><button class="btn" onclick="selectTherapist('${t.id}')">اختيار</button></div>`).join('')}</div><button class="btn secondary" onclick="book()">رجوع</button>`)}
function selectTherapist(id){booking.therapistId=id;chooseDuration()}
function chooseDuration(){render(`${steps(2)}<h2>اختر مدة الجلسة</h2><div class="grid"><div class="card"><h3>30 دقيقة</h3><div class="price">${db.settings.prices[30]} ${db.settings.currency}</div><button class="btn" onclick="selectDuration(30)">اختيار</button></div><div class="card"><h3>60 دقيقة</h3><div class="price">${db.settings.prices[60]} ${db.settings.currency}</div><button class="btn" onclick="selectDuration(60)">اختيار</button></div></div><button class="btn secondary" onclick="chooseTherapist()">رجوع</button>`)}
function selectDuration(d){booking.duration=d;chooseDate()}
function datesForTherapist(){const map=db.availability[booking.therapistId]||{};return Object.keys(map).filter(d=>map[d]?.length).sort()}
function chooseDate(){const dates=datesForTherapist();render(`${steps(3)}<h2>اختر التاريخ</h2>${dates.length?`<div class="grid">${dates.map(d=>`<div class="card"><h3>${formatDate(d)}</h3><p>${therapist().name} — ${booking.duration} دقيقة</p><button class="btn" onclick="chooseTime('${d}')">عرض المواعيد</button></div>`).join('')}</div>`:'<div class="notice">لا توجد مواعيد متاحة لهذا الأخصائي حالياً.</div>'}<button class="btn secondary" onclick="chooseDuration()">رجوع</button>`)}
function mins(t){const[a,b]=t.split(':').map(Number);return a*60+b} function addM(t,n){const v=mins(t)+n;return String(Math.floor(v/60)).padStart(2,'0')+':'+String(v%60).padStart(2,'0')}
function overlap(a,d,b,bd){return mins(a)<mins(b)+bd&&mins(b)<mins(a)+d}
function available(date,duration){const slots=(db.availability[booking.therapistId]||{})[date]||[];return slots.filter(t=>!db.bookings.some(b=>b.therapistId===booking.therapistId&&b.date===date&&b.status!=='Cancelled'&&overlap(t,duration,b.time,b.duration))&&(duration!==60||slots.includes(addM(t,30))))}
function chooseTime(date){booking.date=date;const slots=((db.availability[booking.therapistId]||{})[date])||[];const av=available(date,booking.duration);render(`${steps(4)}<h2>اختر الوقت</h2><p>${formatDate(date)} — ${esc(therapist().name)}</p><div class="slots">${slots.map(t=>`<button class="slot ${av.includes(t)?'':'busy'}" ${av.includes(t)?`onclick="clientData('${t}')"`:'disabled'}>${t}</button>`).join('')}</div><button class="btn secondary" onclick="chooseDate()">رجوع</button>`)}
function therapist(){return therapists.find(t=>t.id===booking.therapistId)||therapists[0]} function service(){return services.find(s=>s.id===booking.serviceId)||services[0]}
function clientData(time){booking.time=time;render(`${steps(5)}<h2>بيانات الحجز</h2><div class="card form"><input id="clientName" class="input" placeholder="الاسم الكامل" autocomplete="name"><input id="clientPhone" class="input" placeholder="رقم الهاتف" inputmode="tel" autocomplete="tel"><input id="clientEmail" class="input" placeholder="البريد الإلكتروني (اختياري)" type="email" autocomplete="email"><label><input type="checkbox" id="consent"> أوافق على سياسة الخصوصية وشروط الحجز.</label><div class="notice summary"><b>ملخص الحجز</b><br>${service().name}<br>${therapist().name}<br>${booking.duration} دقيقة — ${formatDate(booking.date)} — ${booking.time}<br><b>${db.settings.prices[booking.duration]} ${db.settings.currency}</b></div><button class="btn" onclick="confirmBooking()">تأكيد الحجز</button><button class="btn secondary" onclick="chooseTime('${booking.date}')">رجوع</button></div>`)}
function confirmBooking(){const name=document.getElementById('clientName').value.trim(),phone=document.getElementById('clientPhone').value.trim(),email=document.getElementById('clientEmail').value.trim(),consent=document.getElementById('consent').checked;if(!name||!phone||!consent){alert('يرجى إدخال الاسم ورقم الهاتف والموافقة على الشروط.');return}if(!available(booking.date,booking.duration).includes(booking.time)){alert('هذا الموعد لم يعد متاحاً.');chooseTime(booking.date);return}const id='MC-'+Date.now().toString().slice(-8);db.bookings.push({id,name,phone,email,serviceId:booking.serviceId,therapistId:booking.therapistId,duration:booking.duration,date:booking.date,time:booking.time,price:db.settings.prices[booking.duration],status:'Confirmed',created:new Date().toISOString()});save();render(`<section class="hero"><h2>✓ تم حجز موعدك بنجاح</h2><p>${service().name}<br>${therapist().name}<br>${formatDate(booking.date)} — ${booking.time}<br>جلسة ${booking.duration} دقيقة</p><p>رقم الحجز: <b>${id}</b></p><button class="btn" onclick="go('appointments')">مواعيدي</button><button class="btn secondary" onclick="go('home')">الرئيسية</button></section>`)}
function appointments(){render(`<h2>مواعيدي</h2>${db.bookings.length?`<div class="grid">${db.bookings.map(b=>`<div class="card"><h3>${formatDate(b.date)} — ${b.time}</h3><p>${esc(serviceBy(b.serviceId).name)}<br>${esc(therapistBy(b.therapistId).name)}<br>${b.duration} دقيقة — ${b.price} ${db.settings.currency}</p><span class="badge">${esc(b.status)}</span><p class="muted">رقم الحجز: ${esc(b.id)}</p></div>`).join('')}</div>`:'<div class="card">لا توجد حجوزات محفوظة على هذا الجهاز.</div>'}`)}
function serviceBy(id){return services.find(s=>s.id===id)||services[0]} function therapistBy(id){return therapists.find(t=>t.id===id)||therapists[0]}
function admin(){render(`<h2>لوحة الإدارة — نموذج أولي</h2><div class="notice warning">تنبيه: هذه الصفحة غير مؤمّنة وتعمل داخل المتصفح فقط. لا تستخدمها لبيانات مرضى حقيقية.</div><div class="grid"><div class="card"><h3>إضافة مواعيد</h3><div class="form"><select id="avTherapist" class="select">${therapists.map(t=>`<option value="${t.id}">${t.name}</option>`).join('')}</select><input id="availabilityDate" class="input" type="date"><input id="startTime" class="input" type="time"><input id="endTime" class="input" type="time"><button class="btn" onclick="addAvailability()">إضافة</button></div></div><div class="card"><h3>الأسعار</h3><div class="form"><input id="price30" class="input" type="number" value="${db.settings.prices[30]}"><input id="price60" class="input" type="number" value="${db.settings.prices[60]}"><button class="btn" onclick="savePrices()">حفظ الأسعار</button></div></div></div><h2>الحجوزات</h2><div class="table-wrapper"><table class="table"><tr><th>العميل</th><th>الأخصائي</th><th>التاريخ</th><th>الوقت</th><th>الخدمة</th><th>الحالة</th></tr>${db.bookings.map(b=>`<tr><td>${esc(b.name)}</td><td>${esc(therapistBy(b.therapistId).name)}</td><td>${esc(b.date)}</td><td>${esc(b.time)}</td><td>${esc(serviceBy(b.serviceId).name)}</td><td>${esc(b.status)}</td></tr>`).join('')}</table></div>`)}
function addAvailability(){const tid=document.getElementById('avTherapist').value,date=document.getElementById('availabilityDate').value,start=document.getElementById('startTime').value,end=document.getElementById('endTime').value;if(!date||!start||!end||mins(end)<=mins(start)){alert('يرجى إدخال تاريخ ووقت صحيحين.');return}const slots=[];for(let t=mins(start);t<mins(end);t+=30)slots.push(addM('00:00',t));db.availability[tid]??={};db.availability[tid][date]=[...new Set([...(db.availability[tid][date]||[]),...slots])].sort();save();admin()}
function savePrices(){db.settings.prices[30]=Number(document.getElementById('price30').value)||0;db.settings.prices[60]=Number(document.getElementById('price60').value)||0;save();admin()}
function formatDate(d){return new Date(d+'T00:00:00').toLocaleDateString('ar-EG',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}
function router(){const p=location.hash.replace('#','')||'home';({home,book,appointments,admin}[p]||home)()}addEventListener('hashchange',router);router();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.error);
